markdown: kramdown
pygments: true
safe: false
permalink: /blog/:year/:month/:day/:title
exclude:
  - README.md

host: towerjoo.github.io

custom:
    category:
        thoughts: 所思所想
        detail: 点滴技术
        ideas: 创意想法
        others: 分类之外
    categories:
      - name:  toughts
        title: 所思所想

      - name:  detail
        title: 点滴技术

      - name:  ideas
        title: 创意想法

      - name:  others
        title: 分类之外

meta:
    authors:
      - name: Tower Joo
        email: zhutao.iscas@gmail.com
        gravatar: 1cd8c12591616d8c22aaa624f8c07834

    gravatar:
        base: http://www.gravatar.com/avatar/
        param: ?s=
